// Lexer.cpp generated by reflex 6.0.0 from D:\Libs\reflex-6.0.0\bin\win32\cBits.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_header_file         "Lexer.h"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "Lexer.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS INCLUDE                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "Lexer.h"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 6 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

cb::Token Lexer::lex()
{
  static const char *REGEX_INITIAL = "(?m)((?:\\QRead\\E))|((?:\\QPC_mux\\E))|((?:\\QPC_enb\\E))|((?:\\QPC_load\\E))|((?:\\QMDR_we\\E))|((?:\\QMDR_out\\E))|((?:\\QIR_we\\E))|((?:\\QIR_out\\E))|((?:\\QTEMP_we\\E))|((?:\\QTEMP_out\\E))|((?:\\QPosta_we\\E))|((?:\\QPosta_out\\E))|((?:\\QADR_we\\E))|((?:\\QADR_out\\E))|((?:\\QI3B\\E))|((?:\\QMAR_load\\E))|((?:\\QMAR_we\\E))|((?:\\QACC_we\\E))|((?:\\QFR_cls\\E))|((?:\\QALU_in\\E))|((?:\\QALU_out\\E))|((?:\\QREG_out\\E))|((?:\\QREG_in\\E))|((?:\\Q@\\E))|((?:\\Q{\\E))|((?:\\Q}\\E))|((?:\\Q#\\E))|((?:\\Q//\\E).*)|([\\x09\\x0a\\x20]+)|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
		int rule = matcher().scan();
        std::string yytext = matcher().text();
	  
        switch (rule)
        {
          case 0:
            if (matcher().at_end())
            {
                return cb::Token{ "EOF", cb::TokenType::ENDOFFILE };
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:17: "Read" :
#line 17 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::Read};

            break;
          case 2: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:19: "PC_mux" :
#line 19 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::PC_mux};

            break;
          case 3: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:21: "PC_enb" :
#line 21 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::PC_enb};
            break;
          case 4: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:22: "PC_load" :
#line 22 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::PC_load};

            break;
          case 5: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:24: "MDR_we" :
#line 24 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::MDR_we};
            break;
          case 6: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:25: "MDR_out" :
#line 25 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::MDR_out};
            break;
          case 7: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:26: "IR_we" :
#line 26 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::IR_we};
            break;
          case 8: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:27: "IR_out" :
#line 27 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::IR_out};
            break;
          case 9: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:28: "TEMP_we" :
#line 28 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::TEMP_we};
            break;
          case 10: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:29: "TEMP_out" :
#line 29 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::TEMP_out};
            break;
          case 11: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:30: "Posta_we" :
#line 30 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::Posta_we};
            break;
          case 12: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:31: "Posta_out" :
#line 31 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::Posta_out};
            break;
          case 13: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:32: "ADR_we" :
#line 32 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::ADR_we};
            break;
          case 14: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:33: "ADR_out" :
#line 33 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::ADR_out};

            break;
          case 15: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:35: "I3B" :
#line 35 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::I3B};
            break;
          case 16: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:36: "MAR_load" :
#line 36 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::MAR_load};
            break;
          case 17: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:37: "MAR_we" :
#line 37 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::MAR_we};
            break;
          case 18: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:38: "ACC_we" :
#line 38 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::ACC_we};

            break;
          case 19: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:40: "FR_cls" :
#line 40 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::FR_cls};//flag reg
            break;
          case 20: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:41: "ALU_in" :
#line 41 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::ALU_in};
            break;
          case 21: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:42: "ALU_out" :
#line 42 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::ALU_out};

            break;
          case 22: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:44: "REG_out" :
#line 44 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::REG_out};
            break;
          case 23: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:45: "REG_in" :
#line 45 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::REG_in};

            break;
          case 24: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:47: "@" :
#line 47 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::COMMENT};
            break;
          case 25: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:48: "{" :
#line 48 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::LPAREN};
            break;
          case 26: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:49: "}" :
#line 49 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::RPAREN};

            break;
          case 27: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:51: "#" :
#line 51 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
return cb::Token{yytext, cb::TokenType::HASH};


            break;
          case 28: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:54: "//".* :
#line 54 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
{ /* skip comment */ }
            break;
          case 29: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:55: [ \t\n]+ :
#line 55 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
{ /* skip whitespace */ }
            break;
          case 30: // rule D:\Libs\reflex-6.0.0\bin\win32\cBits.l:56: . :
#line 56 "D:\\Libs\\reflex-6.0.0\\bin\\win32\\cBits.l"
          {
              std::string line = matcher().line();
              line.erase(0, line.find_first_not_of(" \t"));

              std::cout << "*******\nTOKEN: UNKNOWN (" << line << ") line number[" << matcher().lineno() << "]\n*******\n";
              return cb::Token{ yytext, cb::TokenType::UNKNOWN };
          }
            break;
        }
  }
}
